#!/usr/bin/env python3
"""Generate and safely deploy the KlipperFleet sudoers file.

Usage: python3 setup_sudoers.py <username>

Auto-discovers binary paths, deduplicates /bin vs /usr/bin symlinks,
and validates via visudo before deploying — a broken file can never
lock out sudo.
"""
import os
import shutil
import subprocess
import sys
import tempfile

def main():
    if len(sys.argv) < 2:
        print("Usage: setup_sudoers.py <username>", file=sys.stderr)
        sys.exit(1)

    user = sys.argv[1]
    sudoers_dest = "/etc/sudoers.d/klipperfleet"

    # Define the commands KlipperFleet needs passwordless sudo for.
    # Each entry is (binary_name, argument_pattern).
    COMMANDS = [
        ("systemctl", "start klipper*"),
        ("systemctl", "stop klipper*"),
        ("systemctl", "restart klipper*"),
        ("systemctl", "start moonraker*"),
        ("systemctl", "stop moonraker*"),
        ("systemctl", "restart moonraker*"),
        ("cp", "* /usr/local/bin/klipper_mcu"),
        ("chmod", "+x /usr/local/bin/klipper_mcu"),
        ("fuser", "*"),
        ("ip", "link set can*"),
        ("dfu-util", "*"),
    ]

    lines = [
        "# KlipperFleet: Allow the service user to manage klipper/moonraker services",
        "# and flash firmware without a password prompt (required for non-interactive",
        "# service operation). Auto-generated by install.sh — do not edit manually.",
    ]
    for binary, args in COMMANDS:
        for path in _find_paths(binary):
            lines.append(f"{user} ALL=(ALL) NOPASSWD: {path} {args}")

    content = "\n".join(lines) + "\n"

    # Write to a temp file and validate with visudo before deploying.
    fd, tmp = tempfile.mkstemp(prefix="klipperfleet-sudoers-")
    try:
        os.write(fd, content.encode())
        os.close(fd)
        os.chmod(tmp, 0o440)

        result = subprocess.run(
            ["visudo", "-cf", tmp],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            print("KlipperFleet: ERROR: Generated sudoers file failed validation!", file=sys.stderr)
            print(f"  visudo output: {result.stderr.strip()}", file=sys.stderr)
            print("  Skipping sudoers install to avoid locking out sudo.", file=sys.stderr)
            sys.exit(1)

        shutil.move(tmp, sudoers_dest)
        os.chmod(sudoers_dest, 0o440)
        print(f"KlipperFleet: Sudoers configured at {sudoers_dest}")
    except Exception:
        # Clean up temp file on any unexpected error
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


def _find_paths(binary):
    """Return deduplicated real paths for a binary (handles /bin -> /usr/bin symlinks)."""
    candidates = [
        f"/usr/bin/{binary}",
        f"/bin/{binary}",
        f"/usr/sbin/{binary}",
        f"/sbin/{binary}",
    ]
    seen_real = set()
    paths = []
    for c in candidates:
        if os.path.exists(c):
            real = os.path.realpath(c)
            if real not in seen_real:
                seen_real.add(real)
                paths.append(c)
    # Fallback: if nothing found on disk, use shutil.which
    if not paths:
        w = shutil.which(binary)
        if w:
            paths.append(w)
    return paths


if __name__ == "__main__":
    main()
